// Assembly ExhibFlat.UI.Common.Controls, Version 2.1.4907.25194

[assembly: System.Web.UI.WebResource("ExhibFlat.UI.Common.Controls.ImageUploader.images.upload.png", "image/png")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Web.UI.WebResource("ExhibFlat.UI.Common.Controls.ImageUploader.css.style.css", "text/css")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCompany("杭州导向科技有限公司")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 2002 - 2011 Hishop. All Rights Reserved.")]
[assembly: System.Reflection.AssemblyProduct("Hishop")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.1")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyDescription("Release")]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyTitle("UI.Common.Controls")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("fa868943-3fd1-475f-9966-995403994b49")]
[assembly: System.Web.UI.WebResource("ExhibFlat.UI.Common.Controls.region.helper.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("ExhibFlat.UI.Common.Controls.ImageUploader.script.upload.js", "text/javascript")]

